version: '3'
services:
  app:
    build: ./app_v1
    ports:
      - "5001:5000"
  nginx:
    image: nginx
    volumes:
      -  ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
